name: TraincartsDynmap
version: @version@
main: net.wolvhaven.traincartsdynmap.TraincartsDynmap
api-version: 1.16
depend: [ Train_Carts, dynmap ]
authors: [ Underscore11 ]
description: Renders Traincarts trains on Dynmap
